import React from "react";
import Head from "next/head";

export const Meta = () => {
	return (
		<Head>
			<title>Audiophile</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};
